# Generated by Django 6.0.4 on 2026-04-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='insects/')),
            ],
        ),
    ]
