# Generated by Django 6.0.4 on 2026-04-17 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('slug', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'content_family',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ContentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('common_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('slug', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'content_order',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ContentSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=150, unique=True)),
                ('common_name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField()),
                ('diet', models.TextField()),
                ('lifespan', models.TextField()),
                ('conservation_status', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geographical_scope', models.CharField(max_length=255)),
                ('main_image', models.ImageField(max_length=500, upload_to='')),
                ('slug', models.CharField(max_length=150, unique=True)),
                ('habitat', models.TextField()),
            ],
            options={
                'db_table': 'content_species',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Insect',
        ),
        migrations.AddField(
            model_name='contentfamily',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insects.contentorder'),
        ),
        migrations.AddField(
            model_name='contentspecies',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insects.contentfamily'),
        ),
    ]
